version: '3.3'

services:

  sample:
    container_name: vortex-2020-frontend
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '9224:3000'
    environment:
      - NODE_ENV=development
